name: "Podcast Generator"
author: "Ray Villalobos"
description: "Generats a feed for a potcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding: 
  icon: "git-brand"
  color: "red"
inputs:
  email: 
    description: The commiter's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The commiter's name
    required: true
    default: ${{ github.actor }}